Repository micrometer-metrics/tracing, pull requests merged in 2022-09, with the labels that each got.

#55 Changes required by Spring Boot Autoconfiguration for MDC
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/CompositePropagationFactory.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/CompositePropagationFactorySupplier.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/W3CPropagation.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/Slf4JBaggageEventListener.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/propagation/CompositeTextMapPropagator.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/propagation/CompositeTextMapPropagatorTest.java
Labels: enhancement, breaking-change

#58 Sets an error status on OTel span when recording an exception
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpan.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/OtelSpanTests.java
Labels: enhancement

#59 Add event handlings to "Propagating[Sender|Receiver]TracingObservatinnHandler"
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/handler/PropagatingReceiverTracingObservationHandlerBraveTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/handler/PropagatingSenderTracingObservationHandlerBraveTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/handler/PropagatingReceiverTracingObservationHandlerOtelTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/handler/PropagatingSenderTracingObservationHandlerOtelTests.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingReceiverTracingObservationHandler.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/handler/PropagatingSenderTracingObservationHandler.java
Labels: enhancement

#62 Checking if span is valid before attaching the baggage to the context
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/Slf4JBaggageEventListener.java
Labels: bug

#60 Use epoch milli to check span start/stop
  micrometer-tracing-tests/micrometer-tracing-test/src/main/java/io/micrometer/tracing/test/simple/SimpleTracer.java
  micrometer-tracing-tests/micrometer-tracing-test/src/main/java/io/micrometer/tracing/test/simple/SpanAssert.java
Labels: bug

#57 Move registry creation to @BeforeEach in SampleTestRunner
  micrometer-tracing-tests/micrometer-tracing-integration-test/src/main/java/io/micrometer/tracing/test/SampleTestRunner.java
Labels: breaking-change

#70 Adapt API change in "Context#getParentObservation"
  micrometer-tracing/src/main/java/io/micrometer/tracing/handler/TracingObservationHandler.java
Labels: enhancement

#71 Fixes invalid Baggage propagation for W3C with Brave
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/build.gradle
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BraveBaggageFields.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BravePropagator.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/W3CPropagation.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/W3CBaggagePropagatorTest.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/W3CPropagationTest.java
Labels: bug

#72 W3CPropagation allows not having baggage
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/W3CPropagation.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/W3CPropagationTest.java
Labels: enhancement

#73 Rename DocumentedSpan to SpanDocumentation
  micrometer-tracing/src/main/java/io/micrometer/tracing/docs/SpanDocumentation.java
Labels: breaking-change, task

#74 Adding a NoOp BaggageManager and allowing its usage in Tracers
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/BraveTracer.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/main/java/io/micrometer/tracing/brave/bridge/W3CPropagation.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/W3CBaggagePropagatorTest.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelTracer.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/BaseTests.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/BaggageInScope.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/BaggageManager.java
Labels: enhancement
