Repository micrometer-metrics/tracing, pull requests merged in 2023-02, with the labels that each got.

#152 Adding onScopeReset method to TracingObservationHandler
  build.gradle
  dependencies.gradle
  micrometer-tracing-bom/gradle.lockfile
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/gradle.lockfile
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/gradle.lockfile
  micrometer-tracing-reporters/micrometer-tracing-reporter-wavefront/gradle.lockfile
  micrometer-tracing-tests/micrometer-tracing-integration-test/gradle.lockfile
  micrometer-tracing-tests/micrometer-tracing-test/gradle.lockfile
  micrometer-tracing/gradle.lockfile
  micrometer-tracing/src/main/java/io/micrometer/tracing/handler/TracingObservationHandler.java
  micrometer-tracing/src/test/java/io/micrometer/tracing/handler/TracingObservationHandlerTests.java
Labels: bug

#170 Use awaitility instead of Thread.sleep in tests
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/build.gradle
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/gradle.lockfile
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/handler/DefaultTracingObservationHandlerBraveTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/build.gradle
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/gradle.lockfile
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/handler/DefaultTracingObservationHandlerOtelTests.java
Labels: type: task

#176 Fix NPE from SimpleTracer#createBaggage
  micrometer-tracing-tests/micrometer-tracing-test/src/main/java/io/micrometer/tracing/test/simple/SimpleBaggageManager.java
Labels: bug, module: tracing-test
