Repository micrometer-metrics/tracing, pull requests merged in 2024-09, with the labels that each got.

#828 Upgrade OTel instrumentation BOM to 2.7.0-alpha
  gradle/libs.versions.toml
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/build.gradle
  micrometer-tracing-reporters/micrometer-tracing-reporter-wavefront/build.gradle
  micrometer-tracing-tests/micrometer-tracing-integration-test/build.gradle
Labels: dependency-upgrade, java

#810 Use TestObservationRegistry in context propagation tests
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/contextpropagation/NestedScopesTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/contextpropagation/ScopesTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/contextpropagation/NestedScopesTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/contextpropagation/ScopesTests.java
Labels: type: task

#817 Support list values in tags in Span and SpanCustomizer
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/BraveFinishedSpanTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/BraveSpanBuilderTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-brave/src/test/java/io/micrometer/tracing/brave/bridge/BraveSpanTest.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelFinishedSpan.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpan.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/main/java/io/micrometer/tracing/otel/bridge/OtelSpanBuilder.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/OtelFinishedSpanTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/OtelSpanBuilderTests.java
  micrometer-tracing-bridges/micrometer-tracing-bridge-otel/src/test/java/io/micrometer/tracing/otel/bridge/OtelSpanTests.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/Span.java
  micrometer-tracing/src/main/java/io/micrometer/tracing/exporter/FinishedSpan.java
Labels: enhancement
